--- #YAML:1.0
name:               Net-IP-XS
version:            0.11
abstract:           IPv4/IPv6 address library
author:
    - Tom Harrison <tomhrr@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Capture::Stderr:  0
    IP::Authority:        0
    Math::BigInt:         0
    Test::More:           0
    Tie::Simple:          0
resources:
    repository:  https://github.com/tomhrr/p5-Net-IP-XS
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
