--- #YAML:1.0
name:               Net-IP-XS
version:            0.01
abstract:           XS implementation of Net::IP
author:
    - Tom Harrison <tomhrr@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Capture::Stderr:  0
    IP::Authority:        0
    Math::BigInt:         0
    Test::More:           0
    Tie::Hash::Sorted:    0
    Tie::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
